site:
  name: "Example Project"
  v3_current: "v3.20.1"
  v3_pre_release: "v3.21.0-alpha.1"
  v3_next: "v3.21.0"
  v3_next_date: 2025-12-12
  v4_current: null
  v4_pre_release: "v4.0.0-alpha.3"
  v4_next: "v4.0.0"
  v4_next_date: null
