name: Update Version

on:
  repository_dispatch:
    types: [version-released]

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Extract version info
        id: version
        run: |
          VERSION="${{ github.event.client_payload.version }}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

          MAJOR=$(echo "$VERSION" | cut -d. -f1 | sed 's/v//')
          MINOR=$(echo "$VERSION" | cut -d. -f2)
          PATCH=$(echo "$VERSION" | cut -d. -f3 | cut -d'-' -f1)

          if [[ "$VERSION" == *"-"* ]]; then
            NEXT_MINOR="v$MAJOR.$MINOR.$PATCH"
          else
            NEXT_MINOR="v$MAJOR.$((MINOR+1)).0"
          fi
          echo "next_version=$NEXT_MINOR" >> $GITHUB_OUTPUT

      - name: Create update branch
        run: |
          BRANCH="update-${{ steps.version.outputs.version }}"

          git fetch origin
          if git show-ref --verify --quiet refs/remotes/origin/"$BRANCH"; then
            echo "Deleting existing remote branch $BRANCH"
            git push origin --delete "$BRANCH"
          fi

          git checkout -b "$BRANCH"
          echo "branch=$BRANCH" >> $GITHUB_ENV

      - name: Update config
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          NEXT="${{ steps.version.outputs.next_version }}"
          MAJOR=$(echo "$VERSION" | cut -d. -f1 | sed 's/v//')
          MINOR=$(echo "$VERSION" | cut -d. -f2)
          PATCH=$(echo "$VERSION" | cut -d. -f3 | cut -d'-' -f1)

          if [[ "$VERSION" == *"-"* ]]; then
            # Pre-release: update pre_release field, clear current if this is the first release
            if [[ "$MAJOR" == "3" ]]; then
              sed -i "s/v3_pre_release: .*/v3_pre_release: \"$VERSION\"/" docs/config.yml
            else
              sed -i "s/v4_pre_release: .*/v4_pre_release: \"$VERSION\"/" docs/config.yml
            fi
          else
            # Stable release: update current field, clear pre_release
            if [[ "$MAJOR" == "3" ]]; then
              sed -i "s/v3_current: .*/v3_current: \"$VERSION\"/" docs/config.yml
              sed -i "s/v3_pre_release: .*/v3_pre_release: null/" docs/config.yml
              # Only update next_minor for minor releases (not patches)
              if [[ "$PATCH" == "0" ]]; then
                sed -i "s/v3_next_minor: .*/v3_next_minor: \"$NEXT\"/" docs/config.yml
              fi
            else
              sed -i "s/v4_current: .*/v4_current: \"$VERSION\"/" docs/config.yml
              sed -i "s/v4_pre_release: .*/v4_pre_release: null/" docs/config.yml
              # Only update next_minor for minor releases (not patches)
              if [[ "$PATCH" == "0" ]]; then
                sed -i "s/v4_next_minor: .*/v4_next_minor: \"$NEXT\"/" docs/config.yml
              fi
            fi
          fi

      - name: Add to versions table
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          DATE=$(date +%Y-%m-%d)
          MAJOR=$(echo "$VERSION" | cut -d. -f1 | sed 's/v//')

          if [[ "$MAJOR" == "4" ]]; then
            # Insert after header for v4 versions (top of table)
            sed -i "/|---|---|/a | $VERSION | $DATE |" docs/versions.md
          else
            # Insert before first v3 version or at end if no v3 versions exist
            if grep -q "| v3\." docs/versions.md; then
              sed -i "0,/| v3\./{s/| v3\./| $VERSION | $DATE |\n&/}" docs/versions.md
            else
              echo "| $VERSION | $DATE |" >> docs/versions.md
            fi
          fi

      - name: Update home page
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          NEXT="${{ steps.version.outputs.next_version }}"
          MAJOR=$(echo "$VERSION" | cut -d. -f1 | sed 's/v//')
          MINOR=$(echo "$VERSION" | cut -d. -f2)
          PATCH=$(echo "$VERSION" | cut -d. -f3 | cut -d'-' -f1)

          if [[ "$VERSION" == *"-"* ]]; then
            # Pre-release: update pre-release line, no date for next minor
            if [[ "$MAJOR" == "3" ]]; then
              sed -i "s/- Pre-release: v3\.[0-9]\+\.[0-9]\+.*/- Pre-release: $VERSION/" docs/index.md
              sed -i "s/- Next: v3\.[0-9]\+\.[0-9]\+ .*/- Next: $NEXT/" docs/index.md
            else
              sed -i "s/- Pre-release: v4\.[0-9]\+\.[0-9]\+.*/- Pre-release: $VERSION/" docs/index.md
              sed -i "s/- Next: v4\.[0-9]\+\.[0-9]\+ .*/- Next: $NEXT/" docs/index.md
            fi
          else
            # Stable release: update current line
            if [[ "$MAJOR" == "3" ]]; then
              sed -i "s/- Current: v3\.[0-9]\+\.[0-9]\+/- Current: $VERSION/" docs/index.md
              # Only update next version and date for minor releases (not patches)
              if [[ "$PATCH" == "0" ]]; then
                NEXT_DATE=$(date -d "+4 months" +%B\ %d,\ %Y)
                sed -i "s/- Next: v3\.[0-9]\+\.[0-9]\+ .*/- Next: $NEXT ($NEXT_DATE)/" docs/index.md
              fi
            else
              sed -i "s/- Current: v4\.[0-9]\+\.[0-9]\+/- Current: $VERSION/" docs/index.md
              # Only update next version and date for minor releases (not patches)
              if [[ "$PATCH" == "0" ]]; then
                NEXT_DATE=$(date -d "+4 months" +%B\ %d,\ %Y)
                sed -i "s/- Next: v4\.[0-9]\+\.[0-9]\+ .*/- Next: $NEXT ($NEXT_DATE)/" docs/index.md
              fi
            fi
          fi

      - name: Commit and create PR
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          git add .
          git commit -s -m "Update docs for ${{ steps.version.outputs.version }}"
          git push origin "${{ env.branch }}"

          gh pr create \
            --title "Update docs for ${{ steps.version.outputs.version }}" \
            --body "Automated documentation update for release ${{ steps.version.outputs.version }}" \
            --base main \
            --head "${{ env.branch }}"
